### ISSUE TITLE
logo blocking tutorials category choice

### ISSUE THREAD

**Issue by Xephobia** [BlackGoku36/BG36-tutorials#1]
The "BG36 Tutorials" is blocking the button of "armory" "iron" and "kha" on mobile meaning we can only read armory tutorials on mobile. It bugs too when having the PC view enabled in chrome
![Screenshot_20200416-231817](https://user-images.githubusercontent.com/28755060/79507777-98e6ae00-8038-11ea-99ee-6e8775f04af1.png)
![Screenshot_20200416-231802](https://user-images.githubusercontent.com/28755060/79507786-9d12cb80-8038-11ea-80cc-e743ad493308.png)

**Comment by BlackGoku36** [comment]
It isn't designed to be view on Mobile devices. Sorry, I am not that good in web dev. But putting mobile on landscape mode should solve this issue.
